#!/usr/bin/env sh

# original docker build command
echo "overwriting docker push $IMAGE_NAME"

jq -r < ../versions.json 'to_entries | map({runtime: .key, version: .value[]}) | .[] | tostring' | while read jstr
do
  RUNTIME=$(echo $jstr | jq -r '.runtime')
  VERSION=$(echo $jstr | jq -r '.version')
  IMAGE_TAG="${DOCKER_REPO}:${RUNTIME}-${VERSION}-${DOCKER_TAG}"
  echo docker push ${IMAGE_TAG}
  docker push ${IMAGE_TAG}
done