#!/bin/bash

./read-versions ../versions.json | while read str
do
  arr=($str)
  RUNTIME=${arr[0]}
  VERSION=${arr[1]}
  IMAGE_TAG="${DOCKER_REPO}:${RUNTIME}-${VERSION}-${DOCKER_TAG}"
  echo docker push ${IMAGE_TAG}
  docker push ${IMAGE_TAG}
done
